version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: ruby:3.1.3
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0'"
    volumes:
       - ".:/app"
    ports:
      - "3000:3000"
    environment:
      DB_HOST: db
      DB_NAME: orders_api
      DB_USERNAME: postgres
      DB_PASSWORD: 1234
    depends_on:
      - db
      - redis
    networks:
      - orders_api_network

  db:
    image: postgres:15.3
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_USER: postgres
      POSTGRES_DB: orders_api
    ports:
     - '5432:5432'
    volumes:
      - "postgres-data:/var/lib/postgresql/data"
    networks:
      - orders_api_network

  redis:
    image: redis:alpine
    container_name: orders_api_redis
    networks:
      - orders_api_network

volumes:
  postgres-data:

networks:
  orders_api_network:
    driver: bridge
