default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>


development:
  <<: *default
  database: orders_api_development
  username: postgres	
  password: admin
  host: localhost
  port: 5432

test:
  <<: *default
  database: orders_api_test
  username: postgres	
  password: admin
  host: localhost
  port: 5432

production:
  <<: *default
  database: orders_api_production
  username: orders_api
  password: <%= ENV["TESTE_API_DATABASE_PASSWORD"] %>
